//! HTML page assembler for native Bokeh rendering.
//!
//! Assembles the final HTML string for each dashboard page — nav, filter bar,
//! CSS grid with chart/paragraph/table cells, range-tool overview charts, and
//! the Bokeh embed script.

/// A chart or module cell in the CSS grid.
pub struct GridItem {
    /// 1-based CSS grid row.
    pub grid_row: usize,
    /// 1-based CSS grid column start.
    pub grid_col: usize,
    /// CSS column span.
    pub grid_col_span: usize,
    /// Chart title (empty for paragraphs / tables).
    pub title: String,
    /// The HTML content to place inside the container.
    /// For charts this is `<div id="uuid"></div>`; for paragraphs/tables it is
    /// the inline HTML.
    pub content: String,
    /// Whether this is a chart cell (affects whether we render the chart-title heading).
    pub is_chart: bool,
}

/// A filter widget rendered in the filter bar.
pub struct FilterWidgetItem {
    /// The `<div id="uuid"></div>` placeholder Bokeh will fill in.
    pub div: String,
    /// Optional label shown next to a Switch widget.
    pub label: Option<String>,
}

/// Full data needed to render one page.
pub struct PageHtmlData<'a> {
    /// Page title.
    pub title: &'a str,
    /// Number of CSS grid columns.
    pub grid_cols: usize,
    /// Top-level report title (used in browser tab and nav header).
    pub report_title: &'a str,
    /// Pre-built navigation HTML block.
    pub nav_html: &'a str,
    /// `"horizontal"` or `"vertical"`.
    pub nav_style: &'a str,
    /// CDN `<script>`/`<link>` tags or inline Bokeh JS/CSS.
    pub bokeh_resources_html: &'a str,
    /// The `<script>` block that calls `Bokeh.embed.embed_items(...)`.
    pub embed_script: &'a str,
    /// Ordered list of content cells.
    pub grid_items: Vec<GridItem>,
    /// Filter widgets, in order.
    pub filter_widgets: Vec<FilterWidgetItem>,
    /// Extra full-width charts shown above the grid (RangeTool overview figures).
    pub range_tool_overviews: Vec<String>,
}

/// Render a single dashboard page to an HTML string.
pub fn render_page_html(data: &PageHtmlData<'_>) -> String {
    let layout_class = if data.nav_style == "vertical" {
        "layout-vertical"
    } else {
        "layout-horizontal"
    };

    let tab_title = if data.report_title.is_empty() {
        format!("{} — RustToBokeh", escape_html(data.title))
    } else {
        format!(
            "{} — {} — RustToBokeh",
            escape_html(data.report_title),
            escape_html(data.title)
        )
    };

    let filter_bar_html = build_filter_bar(&data.filter_widgets);
    let range_overview_html = build_range_overviews(&data.range_tool_overviews);
    let grid_html = build_grid(data.grid_cols, &data.grid_items);

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{tab_title}</title>
    {bokeh_resources}
    {inline_css}
</head>
<body class="{layout_class}">
{nav_html}
{nav_dropdown_script}
    <div class="page-content">
        <h1>{page_title}</h1>
        <p class="subtitle">
            <span class="tech-badge">Polars</span>
            <span class="tech-badge">Bokeh</span>
            <span class="tech-badge">Rust</span>
        </p>
{range_overview_html}{filter_bar_html}        <div class="grid-layout" style="grid-template-columns: repeat({grid_cols}, 1fr);">
{grid_html}        </div>
        <script>{embed_script}</script>
        <footer>Generated by RustToBokeh</footer>
    </div>
</body>
</html>"#,
        tab_title = tab_title,
        bokeh_resources = data.bokeh_resources_html,
        inline_css = INLINE_CSS,
        layout_class = layout_class,
        nav_html = data.nav_html,
        nav_dropdown_script = NAV_DROPDOWN_SCRIPT,
        page_title = escape_html(data.title),
        range_overview_html = range_overview_html,
        filter_bar_html = filter_bar_html,
        grid_cols = data.grid_cols,
        grid_html = grid_html,
        embed_script = data.embed_script,
    )
}

fn build_filter_bar(items: &[FilterWidgetItem]) -> String {
    if items.is_empty() {
        return String::new();
    }
    let mut html = String::from(
        "        <div class=\"filter-bar\">\n            <span class=\"filter-bar-label\">Filters</span>\n",
    );
    for item in items {
        html.push_str("            <div class=\"filter-widget\">\n");
        if let Some(label) = &item.label {
            html.push_str(&format!(
                "                <label class=\"switch-label\">{div}<span>{label}</span></label>\n",
                div = item.div,
                label = escape_html(label),
            ));
        } else {
            html.push_str(&format!("                {}\n", item.div));
        }
        html.push_str("            </div>\n");
    }
    html.push_str("        </div>\n");
    html
}

fn build_range_overviews(overviews: &[String]) -> String {
    if overviews.is_empty() {
        return String::new();
    }
    let mut html = String::new();
    for div in overviews {
        html.push_str(&format!(
            "        <div class=\"chart-container\" style=\"margin-bottom:16px\">{div}</div>\n"
        ));
    }
    html
}

fn build_grid(_grid_cols: usize, items: &[GridItem]) -> String {
    let mut html = String::new();
    for item in items {
        let title_html = if item.is_chart && !item.title.is_empty() {
            format!(
                "                <h2 class=\"chart-title\">{}</h2>\n",
                escape_html(&item.title)
            )
        } else if !item.title.is_empty() {
            // paragraph/table title uses .module-title class
            format!(
                "                <h2 class=\"module-title\">{}</h2>\n",
                escape_html(&item.title)
            )
        } else {
            String::new()
        };

        html.push_str(&format!(
            "            <div class=\"chart-container\" style=\"grid-row: {row}; grid-column: {col} / span {span};\">\n{title}{content}\n            </div>\n",
            row = item.grid_row,
            col = item.grid_col,
            span = item.grid_col_span,
            title = title_html,
            content = item.content,
        ));
    }
    html
}

pub fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

// ── Bokeh CDN resources ───────────────────────────────────────────────────────

/// Bokeh version used for CDN links.
const BOKEH_VERSION: &str = "3.9.0";

/// Generate CDN `<script>` tags for Bokeh.
///
/// Bokeh 3.x bundles its CSS inside the JS files — no separate stylesheet
/// links are needed.
pub fn bokeh_cdn_resources() -> String {
    format!(
        r#"<script src="https://cdn.bokeh.org/bokeh/release/bokeh-{v}.min.js"></script>
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-{v}.min.js"></script>"#,
        v = BOKEH_VERSION,
    )
}

/// Generate inline `<script>` tags embedding Bokeh JS.
///
/// Bokeh 3.x bundles its CSS inside the JS files — no separate stylesheets
/// are needed.
///
/// The JS assets are read from `vendor/bokeh/` at **compile time** via
/// `include_str!`. Run `bash scripts/setup_vendor.sh` before building with
/// this feature enabled.
///
/// Compiled only when `build.rs` confirms the vendor files are present
/// (`bokeh_vendor_present` cfg). The call site in `mod.rs` returns a
/// helpful runtime error when the cfg is absent.
#[cfg(bokeh_vendor_present)]
pub fn bokeh_inline_resources() -> String {
    const BOKEH_JS: &str = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/vendor/bokeh/bokeh-3.9.0.min.js"
    ));
    const BOKEH_WIDGETS_JS: &str = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/vendor/bokeh/bokeh-widgets-3.9.0.min.js"
    ));

    format!("<script>{BOKEH_JS}</script>\n    <script>{BOKEH_WIDGETS_JS}</script>")
}

// ── Embedded CSS ──────────────────────────────────────────────────────────────

const INLINE_CSS: &str = r#"<style>
        * { box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
            background: #f8f9fa;
            color: #333;
            margin: 0;
            padding: 0;
        }
        /* ── Horizontal nav ────────────────────────────────────────────────── */
        .nav-horizontal {
            background: #fff;
            border-bottom: 1px solid #dde2e8;
            position: sticky;
            top: 0;
            z-index: 100;
            box-shadow: 0 1px 4px rgba(0,0,0,0.06);
        }
        .nav-horizontal .nav-header {
            display: flex;
            align-items: stretch;
            padding: 0 20px;
        }
        .nav-horizontal .nav-report-title {
            font-size: 0.95em;
            font-weight: 700;
            color: #2c3e50;
            white-space: nowrap;
            padding: 0 16px 0 0;
            margin-right: 4px;
            border-right: 2px solid #dde2e8;
            flex-shrink: 0;
            display: flex;
            align-items: center;
        }
        .nav-horizontal .nav-tabs-scroll {
            display: flex;
            align-items: stretch;
            overflow-x: auto;
            scrollbar-width: none;
            -ms-overflow-style: none;
            flex: 1;
        }
        .nav-horizontal .nav-tabs-scroll::-webkit-scrollbar { display: none; }
        .nav-horizontal .nav-tab {
            display: flex;
            align-items: center;
            text-decoration: none;
            padding: 0 14px;
            height: 44px;
            font-size: 0.83em;
            font-weight: 500;
            color: #555;
            white-space: nowrap;
            border-bottom: 3px solid transparent;
            flex-shrink: 0;
            transition: color 0.15s, border-color 0.15s, background 0.15s;
        }
        .nav-horizontal .nav-tab:hover { color: #4C72B0; background: #f0f4fb; border-bottom-color: #a0b8d8; }
        .nav-horizontal .nav-tab.active { color: #4C72B0; font-weight: 700; border-bottom-color: #4C72B0; background: #f0f4fb; }
        .nav-horizontal .nav-dd { position: relative; display: flex; align-items: stretch; flex-shrink: 0; }
        .nav-horizontal .nav-dd-trigger {
            display: flex; align-items: center; gap: 5px; padding: 0 14px; height: 44px;
            border: none; background: none; font-family: inherit; font-size: 0.83em;
            font-weight: 500; color: #555; white-space: nowrap; cursor: pointer;
            border-bottom: 3px solid transparent;
            transition: color 0.15s, border-color 0.15s, background 0.15s;
        }
        .nav-horizontal .nav-dd-trigger .caret { font-size: 0.7em; opacity: 0.55; }
        .nav-horizontal .nav-dd:hover > .nav-dd-trigger,
        .nav-horizontal .nav-dd.open > .nav-dd-trigger { color: #4C72B0; background: #f0f4fb; border-bottom-color: #a0b8d8; }
        .nav-horizontal .nav-dd.has-active > .nav-dd-trigger { color: #4C72B0; font-weight: 700; border-bottom-color: #4C72B0; background: #f0f4fb; }
        .nav-horizontal .nav-dd-menu {
            display: none; position: fixed; background: #fff; border: 1px solid #dde2e8;
            border-radius: 6px; box-shadow: 0 6px 24px rgba(0,0,0,0.12);
            min-width: 190px; z-index: 1000; padding: 4px 0;
        }
        .nav-horizontal .nav-dd-item { display: block; padding: 8px 18px; font-size: 0.83em; font-weight: 500; color: #444; text-decoration: none; white-space: nowrap; transition: background 0.1s, color 0.1s; }
        .nav-horizontal .nav-dd-item:hover { background: #f0f4fb; color: #4C72B0; }
        .nav-horizontal .nav-dd-item.active { background: #f0f4fb; color: #4C72B0; font-weight: 700; }
        .nav-horizontal .nav-dd-divider { border: none; border-top: 1px solid #eee; margin: 4px 0; }
        .nav-horizontal .nav-dd-sub { position: relative; }
        .nav-horizontal .nav-dd-sub-trigger {
            display: flex; justify-content: space-between; align-items: center; width: 100%;
            padding: 8px 14px 8px 18px; border: none; background: none; font-family: inherit;
            font-size: 0.83em; font-weight: 500; color: #444; white-space: nowrap; cursor: pointer;
            transition: background 0.1s, color 0.1s; text-align: left;
        }
        .nav-horizontal .nav-dd-sub-trigger .caret { font-size: 0.7em; opacity: 0.55; }
        .nav-horizontal .nav-dd-sub:hover > .nav-dd-sub-trigger,
        .nav-horizontal .nav-dd-sub.open > .nav-dd-sub-trigger { background: #f0f4fb; color: #4C72B0; }
        .nav-horizontal .nav-dd-sub.has-active > .nav-dd-sub-trigger { color: #4C72B0; font-weight: 700; }
        .nav-horizontal .nav-dd-sub-menu {
            display: none; position: fixed; background: #fff; border: 1px solid #dde2e8;
            border-radius: 6px; box-shadow: 0 6px 24px rgba(0,0,0,0.12); min-width: 190px; z-index: 1001; padding: 4px 0;
        }
        /* ── Vertical nav ──────────────────────────────────────────────────── */
        .nav-vertical { position: fixed; left: 0; top: 0; width: 220px; height: 100vh; overflow-y: auto; background: #2c3e50; z-index: 100; padding-bottom: 24px; }
        .nav-vertical .nav-report-title { color: white; font-size: 0.95em; font-weight: 700; padding: 18px 16px 14px; border-bottom: 1px solid rgba(255,255,255,0.12); line-height: 1.3; }
        .nav-vertical details > summary { list-style: none; display: flex; align-items: center; justify-content: space-between; cursor: pointer; user-select: none; color: rgba(255,255,255,0.45); font-size: 0.67em; font-weight: 700; text-transform: uppercase; letter-spacing: 0.09em; padding: 10px 14px 4px; }
        .nav-vertical details > summary::-webkit-details-marker { display: none; }
        .nav-vertical details > summary::after { content: "▸"; font-size: 0.9em; opacity: 0.6; transition: transform 0.15s; }
        .nav-vertical details[open] > summary::after { transform: rotate(90deg); }
        .nav-vertical .nav-indent { padding-left: 10px; }
        .nav-vertical a { display: block; text-decoration: none; padding: 7px 14px 7px 22px; font-size: 0.85em; font-weight: 500; color: rgba(255,255,255,0.72); transition: background 0.12s, color 0.12s; }
        .nav-vertical a:hover { background: rgba(255,255,255,0.08); color: white; }
        .nav-vertical a.active { background: #4C72B0; color: white; font-weight: 700; }
        .nav-vertical .nav-uncategorized { margin-top: 8px; }
        .nav-vertical .nav-search { padding: 8px 12px 10px; border-bottom: 1px solid rgba(255,255,255,0.08); }
        .nav-vertical .nav-search-input { width: 100%; box-sizing: border-box; background: rgba(255,255,255,0.10); border: 1px solid rgba(255,255,255,0.20); border-radius: 4px; color: white; padding: 6px 8px 6px 28px; font-size: 0.8em; outline: none; background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='rgba(255,255,255,0.5)' stroke-width='2.5' stroke-linecap='round' stroke-linejoin='round'%3E%3Ccircle cx='11' cy='11' r='8'/%3E%3Cline x1='21' y1='21' x2='16.65' y2='16.65'/%3E%3C/svg%3E"); background-repeat: no-repeat; background-position: 8px center; background-size: 14px 14px; }
        .nav-vertical .nav-search-input::placeholder { color: rgba(255,255,255,0.40); }
        .nav-vertical .nav-search-input:focus { background-color: rgba(255,255,255,0.15); border-color: rgba(255,255,255,0.40); }
        /* ── Page layout ───────────────────────────────────────────────────── */
        .layout-horizontal .page-content { max-width: 1600px; margin: 0 auto; padding: 0 20px 40px; }
        .layout-vertical .page-content { margin-left: 220px; padding: 0 24px 40px; }
        h1 { color: #2c3e50; border-bottom: 3px solid #4C72B0; padding-bottom: 12px; margin: 20px 0 8px; }
        .subtitle { color: #666; margin-bottom: 20px; font-size: 0.9em; }
        .grid-layout { display: grid; gap: 20px; margin-bottom: 24px; }
        .chart-container { background: white; border-radius: 8px; padding: 16px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); min-width: 0; }
        .chart-title { color: #2c3e50; font-size: 1.0em; margin: 0 0 10px 0; padding-bottom: 8px; border-bottom: 1px solid #e8eef7; }
        footer { margin-top: 20px; color: #999; font-size: 0.8em; text-align: center; }
        .tech-badge { display: inline-block; background: #e8eef7; color: #4C72B0; border-radius: 4px; padding: 2px 7px; margin: 0 2px; font-weight: 600; font-size: 0.85em; }
        .filter-bar { display: flex; flex-wrap: wrap; gap: 16px; padding: 16px 20px; margin-bottom: 20px; background: white; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); align-items: center; }
        .filter-bar-label { font-weight: 600; color: #4C72B0; font-size: 0.85em; white-space: nowrap; }
        .filter-widget { flex: 1; min-width: 200px; }
        .switch-label { display: flex; align-items: center; gap: 10px; font-size: 0.9em; color: #2c3e50; cursor: pointer; }
        .paragraph-module { height: 100%; box-sizing: border-box; }
        .paragraph-module p { color: #555; line-height: 1.7; margin: 0 0 12px; font-size: 0.95em; }
        .paragraph-module p:last-child { margin-bottom: 0; }
        .table-module { overflow: hidden; }
        .table-wrapper { overflow-x: auto; max-height: 420px; overflow-y: auto; }
        .table-module table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
        .table-module thead th { background: #4C72B0; color: white; padding: 10px 14px; text-align: left; position: sticky; top: 0; white-space: nowrap; font-weight: 600; }
        .table-module tbody tr:nth-child(even) { background: #f8f9fa; }
        .table-module tbody tr:hover { background: #e8eef7; }
        .table-module tbody td { padding: 8px 14px; border-bottom: 1px solid #e9ecef; color: #2c3e50; }
        .module-title { color: #2c3e50; font-size: 1.0em; margin: 0 0 12px; padding-bottom: 8px; border-bottom: 1px solid #e8eef7; font-weight: 600; }
    </style>"#;

const NAV_DROPDOWN_SCRIPT: &str = r#"    <script>
    (function () {
        function showMenu(menu, x, y) {
            clearTimeout(menu._ht);
            menu.style.left = x + 'px';
            menu.style.top  = y + 'px';
            menu.style.display = 'block';
            var vw = window.innerWidth;
            var mw = menu.offsetWidth;
            if (x + mw > vw) menu.style.left = Math.max(0, vw - mw) + 'px';
        }
        function hideMenu(menu) { menu._ht = setTimeout(function () { menu.style.display = 'none'; }, 150); }
        function keepOpen(menu) { clearTimeout(menu._ht); }
        function wire(trigger, menu, openRight) {
            trigger.addEventListener('mouseenter', function () {
                var r = trigger.getBoundingClientRect();
                showMenu(menu, openRight ? r.right : r.left, openRight ? r.top : r.bottom);
            });
            trigger.addEventListener('mouseleave', function () { hideMenu(menu); });
            menu.addEventListener('mouseenter', function () { keepOpen(menu); });
            menu.addEventListener('mouseleave', function () { hideMenu(menu); });
        }
        document.querySelectorAll('.nav-horizontal .nav-dd').forEach(function (dd) {
            var t = dd.querySelector(':scope > .nav-dd-trigger');
            var m = dd.querySelector(':scope > .nav-dd-menu');
            if (!t || !m) return;
            wire(t, m, false);
            t.addEventListener('click', function (e) {
                e.stopPropagation();
                if (m.style.display === 'block') { m.style.display = 'none'; } else { var r = t.getBoundingClientRect(); showMenu(m, r.left, r.bottom); }
            });
        });
        document.querySelectorAll('.nav-horizontal .nav-dd-sub').forEach(function (sub) {
            var t = sub.querySelector(':scope > .nav-dd-sub-trigger');
            var m = sub.querySelector(':scope > .nav-dd-sub-menu');
            if (!t || !m) return;
            wire(t, m, true);
        });
        document.addEventListener('click', function () {
            document.querySelectorAll('.nav-horizontal .nav-dd-menu, .nav-horizontal .nav-dd-sub-menu').forEach(function (m) { m.style.display = 'none'; });
        });
    })();
    (function () {
        var input = document.getElementById('nav-search-input');
        if (!input) return;
        var sidebar = document.querySelector('.nav-vertical');
        if (!sidebar) return;
        sidebar.querySelectorAll('details').forEach(function (d) {
            if (d.open) d.setAttribute('data-was-open', '');
        });
        input.addEventListener('input', function () {
            var q = this.value.trim().toLowerCase();
            var links = sidebar.querySelectorAll('a[href]');
            var details = sidebar.querySelectorAll('details');
            if (!q) {
                links.forEach(function (a) { a.style.display = ''; });
                details.forEach(function (d) { d.style.display = ''; d.open = d.hasAttribute('data-was-open'); });
                return;
            }
            links.forEach(function (a) { a.style.display = 'none'; });
            details.forEach(function (d) { d.style.display = 'none'; });
            links.forEach(function (a) {
                if (a.textContent.trim().toLowerCase().indexOf(q) !== -1) {
                    a.style.display = '';
                    var el = a.parentElement;
                    while (el && el !== sidebar) {
                        if (el.tagName === 'DETAILS') { el.style.display = ''; el.open = true; }
                        el = el.parentElement;
                    }
                }
            });
        });
    })();
    </script>"#;
