//! HTML page assembler for native Bokeh rendering.
//!
//! Assembles the final HTML string for each dashboard page — nav, filter bar,
//! CSS grid with chart/paragraph/table cells, range-tool overview charts, and
//! the Bokeh embed script.

use crate::bokeh_native::html_css_scripts::{INLINE_CSS, NAV_DROPDOWN_SCRIPT};

/// A chart or module cell in the CSS grid.
pub struct GridItem {
    /// 1-based CSS grid row.
    pub grid_row: usize,
    /// 1-based CSS grid column start.
    pub grid_col: usize,
    /// CSS column span.
    pub grid_col_span: usize,
    /// Chart title (empty for paragraphs / tables).
    pub title: String,
    /// The HTML content to place inside the container.
    /// For charts this is `<div id="uuid"></div>`; for paragraphs/tables it is
    /// the inline HTML.
    pub content: String,
    /// Whether this is a chart cell (affects whether we render the chart-title heading).
    pub is_chart: bool,
}

/// A filter widget rendered in the filter bar.
pub struct FilterWidgetItem {
    /// The `<div id="uuid"></div>` placeholder Bokeh will fill in.
    pub div: String,
    /// Optional label shown next to a Switch widget.
    pub label: Option<String>,
}

/// Full data needed to render one page.
pub struct PageHtmlData<'a> {
    /// Page title.
    pub title: &'a str,
    /// Number of CSS grid columns.
    pub grid_cols: usize,
    /// Top-level report title (used in browser tab and nav header).
    pub report_title: &'a str,
    /// Pre-built navigation HTML block.
    pub nav_html: &'a str,
    /// `"horizontal"` or `"vertical"`.
    pub nav_style: &'a str,
    /// CDN `<script>`/`<link>` tags or inline Bokeh JS/CSS.
    pub bokeh_resources_html: &'a str,
    /// The `<script>` block that calls `Bokeh.embed.embed_items(...)`.
    pub embed_script: &'a str,
    /// Ordered list of content cells.
    pub grid_items: Vec<GridItem>,
    /// Filter widgets, in order.
    pub filter_widgets: Vec<FilterWidgetItem>,
    /// Extra full-width charts shown above the grid (RangeTool overview figures).
    pub range_tool_overviews: Vec<String>,
    /// Hidden div UUIDs for non-DOMView roots (BooleanFilter, hoisted CDS,
    /// Range1d widget). BokehJS's `embed_items` calls
    /// `document.getElementById(uuid)` for every entry in `root_ids` and
    /// throws if the element is missing. Emitted as `display:none` divs so
    /// the lookup succeeds; non-DOMView models are skipped for placement but
    /// their presence in the roots list keeps positional indexing aligned.
    pub hidden_divs: Vec<String>,
}

/// Render a single dashboard page to an HTML string.
pub fn render_page_html(data: &PageHtmlData<'_>) -> String {
    let layout_class = if data.nav_style == "vertical" {
        "layout-vertical"
    } else {
        "layout-horizontal"
    };

    let tab_title = if data.report_title.is_empty() {
        format!("{} — RustToBokeh", escape_html(data.title))
    } else {
        format!(
            "{} — {} — RustToBokeh",
            escape_html(data.report_title),
            escape_html(data.title)
        )
    };

    let filter_bar_html = build_filter_bar(&data.filter_widgets);
    let range_overview_html = build_range_overviews(&data.range_tool_overviews);
    let grid_html = build_grid(data.grid_cols, &data.grid_items);
    let hidden_divs_html = build_hidden_divs(&data.hidden_divs);

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{tab_title}</title>
    {bokeh_resources}
    {inline_css}
</head>
<body class="{layout_class}">
{nav_html}
{nav_dropdown_script}
    <div class="page-content">
        <h1>{page_title}</h1>
        <p class="subtitle">
            <span class="tech-badge tech-polars">Polars</span>
            <span class="tech-badge tech-bokeh">Bokeh</span>
            <span class="tech-badge tech-rust">Rust</span>
        </p>
{range_overview_html}{filter_bar_html}        <div class="grid-layout" style="grid-template-columns: repeat({grid_cols}, 1fr);">
{grid_html}        </div>
{hidden_divs_html}        <script>{embed_script}</script>
        <footer>Generated by RustToBokeh</footer>
    </div>
</body>
</html>"#,
        tab_title = tab_title,
        bokeh_resources = data.bokeh_resources_html,
        inline_css = INLINE_CSS,
        layout_class = layout_class,
        nav_html = data.nav_html,
        nav_dropdown_script = NAV_DROPDOWN_SCRIPT,
        page_title = escape_html(data.title),
        range_overview_html = range_overview_html,
        filter_bar_html = filter_bar_html,
        grid_cols = data.grid_cols,
        grid_html = grid_html,
        hidden_divs_html = hidden_divs_html,
        embed_script = data.embed_script,
    )
}

fn build_hidden_divs(uuids: &[String]) -> String {
    if uuids.is_empty() {
        return String::new();
    }
    let mut html = String::from("        <div style=\"display:none\">\n");
    for uuid in uuids {
        html.push_str(&format!("            <div id=\"{uuid}\"></div>\n"));
    }
    html.push_str("        </div>\n");
    html
}

fn build_filter_bar(items: &[FilterWidgetItem]) -> String {
    if items.is_empty() {
        return String::new();
    }
    let mut html = String::from(
        "        <div class=\"filter-bar\">\n            <span class=\"filter-bar-label\">Filters</span>\n",
    );
    for item in items {
        html.push_str("            <div class=\"filter-widget\">\n");
        if let Some(label) = &item.label {
            html.push_str(&format!(
                "                <label class=\"switch-label\">{div}<span>{label}</span></label>\n",
                div = item.div,
                label = escape_html(label),
            ));
        } else {
            html.push_str(&format!("                {}\n", item.div));
        }
        html.push_str("            </div>\n");
    }
    html.push_str("        </div>\n");
    html
}

fn build_range_overviews(overviews: &[String]) -> String {
    if overviews.is_empty() {
        return String::new();
    }
    let mut html = String::new();
    for div in overviews {
        html.push_str(&format!(
            "        <div class=\"chart-container\" style=\"margin-bottom:16px\">{div}</div>\n"
        ));
    }
    html
}

fn build_grid(_grid_cols: usize, items: &[GridItem]) -> String {
    let mut html = String::new();
    for item in items {
        let title_html = if item.is_chart && !item.title.is_empty() {
            format!(
                "                <h2 class=\"chart-title\">{}</h2>\n",
                escape_html(&item.title)
            )
        } else if !item.title.is_empty() {
            // paragraph/table title uses .module-title class
            format!(
                "                <h2 class=\"module-title\">{}</h2>\n",
                escape_html(&item.title)
            )
        } else {
            String::new()
        };

        html.push_str(&format!(
            "            <div class=\"chart-container\" style=\"grid-row: {row}; grid-column: {col} / span {span};\">\n{title}{content}\n            </div>\n",
            row = item.grid_row,
            col = item.grid_col,
            span = item.grid_col_span,
            title = title_html,
            content = item.content,
        ));
    }
    html
}

pub fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

// ── Bokeh CDN resources ───────────────────────────────────────────────────────

/// Bokeh version used for CDN links.
const BOKEH_VERSION: &str = "3.9.0";

/// Generate CDN `<script>` tags for Bokeh.
///
/// Bokeh 3.x bundles its CSS inside the JS files — no separate stylesheet
/// links are needed.
pub fn bokeh_cdn_resources() -> String {
    format!(
        r#"<script src="https://cdn.bokeh.org/bokeh/release/bokeh-{v}.min.js"></script>
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-{v}.min.js"></script>"#,
        v = BOKEH_VERSION,
    )
}

/// Generate inline `<script>` tags embedding Bokeh JS.
///
/// Bokeh 3.x bundles its CSS inside the JS files — no separate stylesheets
/// are needed.
///
/// The JS assets are read from `vendor/bokeh/` at **compile time** via
/// `include_str!`. Run `bash scripts/setup_vendor.sh` before building with
/// this feature enabled.
///
/// Compiled only when `build.rs` confirms the vendor files are present
/// (`bokeh_vendor_present` cfg). The call site in `mod.rs` returns a
/// helpful runtime error when the cfg is absent.
#[cfg(bokeh_vendor_present)]
pub fn bokeh_inline_resources() -> String {
    const BOKEH_JS: &str = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/vendor/bokeh/bokeh-3.9.0.min.js"
    ));
    const BOKEH_WIDGETS_JS: &str = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/vendor/bokeh/bokeh-widgets-3.9.0.min.js"
    ));

    format!("<script>{BOKEH_JS}</script>\n    <script>{BOKEH_WIDGETS_JS}</script>")
}